### Expressions ###
[expressions.eyes]
probability = 0.5
tags = ["open", "half-closed", "wink", "closed[0.4]"]

[expressions.looking]
probability = 0.5
tags = ["at viewer", "away", "up", "down", "back"]

[expressions.mouth]
probability = 0.5
tags = ["open", "half-closed", "closed"]

[expressions.tongue]
probability = 0.2
tags = ["tongue out"]


### SFW ###
[sfw.positions]
probability = 0.7
tags = ["standing", "sitting", "lying", "walking[0.5]", "running[0.3]"]

[sfw.gestures]
probability = 0.7
tags = ["adjusting hair", "waving", "hand on hip", "crossed arms"]


### NSFW ###

# Settings
[nsfw.settings]
insertions = ["vaginal", "anal"]

hide_male = false
penis_sizes = ["small[0.5]", "", "large", "huge[0.5]"]
testicles_sizes = ["small[0.5]", "", "large", "huge[0.5]"]

sweat = 1.0
cum = 1.0
pussy_juice = 1.0

# Actions
[nsfw.acts]
teasing = ["flashing"]
preliminaries = ["fingering", "handjob", "fellatio", "licking penis", "paizuri"]
intercourses = [
  "doggystyle",
  "cowgirl",
  "reversed cowgirl",
  "piledriver",
  "suspended congress",
  "full nelson",
]
