# BODY
[body.colors]
probability = 0.4
list = ["standard_colors", "special_colors?0.5"]
standard_colors = ["dark?1.5", "pale"]
special_colors = ["black", "red", "green", "blue", "purple", "pink"]

[body.types]
probability = 0.5
tags = [
  "petite",
  "slim",
  "skinny",
  "athletic",
  "muscular",
  "curvy",
  "plump",
  "chubby?0.2",
  "fat?0.1",
]

[body.breasts]
sizes = [
  "flat chest",
  "small breasts",
  "medium breasts",
  "large breasts",
  "huge breasts?0.5",
]

[body.breasts.nipples]
probability = 0.5
repeat = [1, 2]
tags = ["dark", "puffy"]

[body.extras]
probability = 0.75
repeat = [1, 3]
tags = ["freckles?2", "tattoos", "piercings", "scars?0.2"]

# HAIR
[hair]
lengths = ["short", "medium", "long", "very long"]

[hair.styles]
probability = 0.8
list = ["styles", "appearances"]
styles = ["ponytail", "bun", "braid", "pigtails"]
appearances = ["curly", "straight", "wavy"]

[hair.colors]
list = ["standard_colors", "special_colors?0.5"]
standard_colors = ["black", "brown", "blonde", "ginger"]
special_colors = [
  "red",
  "blue",
  "aqua",
  "green",
  "grey",
  "white",
  "silver",
  "pink",
  "purple",
]

# EYES & EYEWEAR
[eyes.colors]
list = ["standard_colors", "special_colors?0.8"]
standard_colors = ["black", "brown", "blue", "green"]
special_colors = ["red", "yellow", "orange", "pink", "purple", "grey", "white"]

[eyes.eyewears]
probability = 0.4
types = ["glasses", "sunglasses", "round glasses", "googles"]
colors = [
  "aqua",
  "black",
  "blue",
  "brown",
  "green",
  "grey",
  "orange",
  "pink",
  "purple",
  "red",
  "white",
  "yellow",
]
