# State: how clothed the character is
states = ["clothed", "underwear?0.3", "nude?0.1"]

# Types: if clothed, what type of clothing
types = ["casual", "dress", "swimsuit", "uniform"]

# Colors apply for all piece of clothing
colors = [
  "white",
  "grey",
  "black",
  "brown",
  "red",
  "orange",
  "yellow",
  "green",
  "blue",
  "aqua",
  "purple",
  "pink",
]

# Swimsuit & Uniforms
swimsuit = ["bikini", "one-piece swimsuit"]
uniform = ["school", "sport", "military", "maid"]

# Casual clothing
[casual]
top = ["shirt", "blouse", "sweater", "hoodie"]
bottom = ["jeans", "pants", "shorts", "skirt"]

[casual.vest]
probability = 0.3
tags = ["vest", "coat", "trenchoat", "jacket"]

# Dress
[dress]
length = ["short", "long"]

[dress.style]
probability = 0.5
tags = ["off-shoulder", "backless"]
